"""add_opportunity_id_to_rfqs

Revision ID: 0789980b6f09
Revises: abc8768129ab
Create Date: 2026-07-01 13:57:11.495890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0789980b6f09'
down_revision: Union[str, Sequence[str], None] = 'abc8768129ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('opportunity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rfqs_opportunity_id'), 'rfqs', ['opportunity_id'], unique=False)
    op.create_foreign_key(None, 'rfqs', 'opportunities', ['opportunity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_index(op.f('ix_rfqs_opportunity_id'), table_name='rfqs')
    op.drop_column('rfqs', 'opportunity_id')
    # ### end Alembic commands ###
