"""restore_mailbox_sync_cursor_table

Revision ID: 17aaaedaa220
Revises: 26b535426250
Create Date: 2026-06-18 07:32:10.419203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17aaaedaa220'
down_revision: Union[str, Sequence[str], None] = '26b535426250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_sync_cursor',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('last_history_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox_sync_cursor')
    # ### end Alembic commands ###
