"""gmail_integration_schema_changes

Revision ID: 26b535426250
Revises: h4i5j6k7l8m9
Create Date: 2026-06-17 15:26:55.171493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b535426250'
down_revision: Union[str, Sequence[str], None] = 'h4i5j6k7l8m9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailbox_sync_cursor')
    op.drop_index(op.f('ix_contacts_netsuite_last_modified'), table_name='contacts')
    op.drop_constraint(op.f('uq_contact_netsuite_id'), 'contacts', type_='unique')
    op.drop_index(op.f('ix_contacts_netsuite_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_netsuite_id'), 'contacts', ['netsuite_id'], unique=True)
    op.alter_column('customers', 'companyname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_customers_netsuite_last_modified'), table_name='customers')
    op.drop_index(op.f('ix_customers_salesrep_id'), table_name='customers')
    op.drop_constraint(op.f('uq_customer_netsuite_id'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_netsuite_id'), table_name='customers')
    op.create_index(op.f('ix_customers_netsuite_id'), 'customers', ['netsuite_id'], unique=True)
    op.alter_column('email_tracking', 'attachments_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('email_tracking', 'all_recipients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_email_tracking_customer'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_draft'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_opportunity'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_rfq'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_supplier'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_thread'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_unlinked'), table_name='email_tracking', postgresql_where='(rfq_id IS NULL)')
    op.drop_index(op.f('ix_email_tracking_user'), table_name='email_tracking')
    op.create_index(op.f('ix_email_tracking_customer_id'), 'email_tracking', ['customer_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_gmail_thread_id'), 'email_tracking', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_opportunity_id'), 'email_tracking', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_rfq_id'), 'email_tracking', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_supplier_id'), 'email_tracking', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_user_email'), 'email_tracking', ['user_email'], unique=False)
    op.drop_index(op.f('ix_opportunities_netsuite_last_modified'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_salesrep_id'), table_name='opportunities')
    op.drop_constraint(op.f('uq_opportunity_netsuite_id'), 'opportunities', type_='unique')
    op.drop_index(op.f('ix_opportunities_netsuite_id'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_netsuite_id'), 'opportunities', ['netsuite_id'], unique=True)
    op.drop_index(op.f('ix_rfqs_email_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_last_email_sent_at'), table_name='rfqs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rfqs_last_email_sent_at'), 'rfqs', ['last_email_sent_at'], unique=False)
    op.create_index(op.f('ix_rfqs_email_status'), 'rfqs', ['email_status'], unique=False)
    op.drop_index(op.f('ix_opportunities_netsuite_id'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_netsuite_id'), 'opportunities', ['netsuite_id'], unique=False)
    op.create_unique_constraint(op.f('uq_opportunity_netsuite_id'), 'opportunities', ['netsuite_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_opportunities_salesrep_id'), 'opportunities', ['salesrep_id'], unique=False)
    op.create_index(op.f('ix_opportunities_netsuite_last_modified'), 'opportunities', ['netsuite_last_modified'], unique=False)
    op.drop_index(op.f('ix_email_tracking_user_email'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_supplier_id'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_rfq_id'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_opportunity_id'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_gmail_thread_id'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_customer_id'), table_name='email_tracking')
    op.create_index(op.f('ix_email_tracking_user'), 'email_tracking', ['user_email'], unique=False)
    op.create_index(op.f('ix_email_tracking_unlinked'), 'email_tracking', ['supplier_id', 'customer_id'], unique=False, postgresql_where='(rfq_id IS NULL)')
    op.create_index(op.f('ix_email_tracking_thread'), 'email_tracking', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_supplier'), 'email_tracking', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_rfq'), 'email_tracking', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_opportunity'), 'email_tracking', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_draft'), 'email_tracking', ['gmail_draft_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_customer'), 'email_tracking', ['customer_id'], unique=False)
    op.alter_column('email_tracking', 'all_recipients',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('email_tracking', 'attachments_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_netsuite_id'), table_name='customers')
    op.create_index(op.f('ix_customers_netsuite_id'), 'customers', ['netsuite_id'], unique=False)
    op.create_unique_constraint(op.f('uq_customer_netsuite_id'), 'customers', ['netsuite_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_customers_salesrep_id'), 'customers', ['salesrep_id'], unique=False)
    op.create_index(op.f('ix_customers_netsuite_last_modified'), 'customers', ['netsuite_last_modified'], unique=False)
    op.alter_column('customers', 'companyname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_contacts_netsuite_id'), table_name='contacts')
    op.create_index(op.f('ix_contacts_netsuite_id'), 'contacts', ['netsuite_id'], unique=False)
    op.create_unique_constraint(op.f('uq_contact_netsuite_id'), 'contacts', ['netsuite_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_contacts_netsuite_last_modified'), 'contacts', ['netsuite_last_modified'], unique=False)
    op.create_table('mailbox_sync_cursor',
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_history_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_email', name=op.f('mailbox_sync_cursor_pkey'))
    )
    # ### end Alembic commands ###
