"""add_rfqs_and_rfq_items_tables

Revision ID: 2b0e95950a01
Revises: 39e2882667f4
Create Date: 2026-05-08 14:01:42.963301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b0e95950a01'
down_revision: Union[str, Sequence[str], None] = '39e2882667f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_number', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=False),
    sa.Column('customer_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('netsuite_opportunity', sa.String(), nullable=True),
    sa.Column('hubspot_deal', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_rfq_number'), 'rfqs', ['rfq_number'], unique=True)
    op.create_table('rfq_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('input_description', sa.Text(), nullable=True),
    sa.Column('input_code', sa.String(), nullable=True),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('suppliers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'line', name='uq_rfq_item_line')
    )
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_rfqs_rfq_number'), table_name='rfqs')
    op.drop_table('rfqs')
    # ### end Alembic commands ###
