"""add cost_price and sale_price to rfq_items

Revision ID: 3284fb44c27e
Revises: cf6674c18cc7
Create Date: 2026-07-03 16:10:21.578104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3284fb44c27e'
down_revision: Union[str, Sequence[str], None] = 'cf6674c18cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfq_items', sa.Column('cost_price', sa.Numeric(), nullable=True))
    op.add_column('rfq_items', sa.Column('sale_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfq_items', 'sale_price')
    op.drop_column('rfq_items', 'cost_price')
    # ### end Alembic commands ###
