"""Add currency to suppliers

Revision ID: 519ef06e2a78
Revises: 2b0e95950a01
Create Date: 2026-05-09 13:10:28.011862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519ef06e2a78'
down_revision: Union[str, Sequence[str], None] = '2b0e95950a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'currency')
    # ### end Alembic commands ###
