"""add_sender_email_to_email_tracking

Revision ID: 76bd79cd560f
Revises: 17aaaedaa220
Create Date: 2026-06-20 11:18:54.909376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bd79cd560f'
down_revision: Union[str, Sequence[str], None] = '17aaaedaa220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — data backfill handled by scripts/backfill_sender_email.py."""
    op.add_column('email_tracking', sa.Column('sender_email', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_tracking', 'sender_email')
    # ### end Alembic commands ###
