"""add_customer_id_to_rfqs

Revision ID: abc8768129ab
Revises: j6k7l8m9n0p1
Create Date: 2026-07-01 13:49:40.489169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc8768129ab'
down_revision: Union[str, Sequence[str], None] = 'j6k7l8m9n0p1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rfqs_customer_id'), 'rfqs', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'rfqs', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_index(op.f('ix_rfqs_customer_id'), table_name='rfqs')
    op.drop_column('rfqs', 'customer_id')
    # ### end Alembic commands ###
