"""add supplier_meta jsonb to rfqs

Revision ID: ccb90336b3e7
Revises: 3284fb44c27e
Create Date: 2026-07-07 14:09:08.185992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccb90336b3e7'
down_revision: Union[str, Sequence[str], None] = '3284fb44c27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfqs', sa.Column('supplier_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfqs', 'supplier_meta')
    # ### end Alembic commands ###
