"""add_source_to_suppliers

Revision ID: ce6f6d8bc11f
Revises: 519ef06e2a78
Create Date: 2026-05-12 13:30:47.542978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6f6d8bc11f'
down_revision: Union[str, Sequence[str], None] = '519ef06e2a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('suppliers', sa.Column('source', sa.String(length=20), nullable=True))
    op.execute("UPDATE suppliers SET source = 'netsuite' WHERE source IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'source')
    # ### end Alembic commands ###
