"""add_netsuite_last_modified_to_brands

Revision ID: cf6674c18cc7
Revises: 0789980b6f09
Create Date: 2026-07-03 14:47:59.547386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6674c18cc7'
down_revision: Union[str, Sequence[str], None] = '0789980b6f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('netsuite_last_modified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'netsuite_last_modified')
    # ### end Alembic commands ###
